return {
  ensure_installed = {
    "none-ls",
    "black",
    "debugpy",
    "mypy",
    "ruff-lsp",
    "pyright",
    "eslint-lsp",
    "js-debug-adapter",
    "prettier",
    "typescript-language-server",
    "clangd",
    "clang-format",
    "codelldb",
    "lua-language-server",
    "stylua",
    "html-lsp",
    "css-lsp",
    "jdtls",
  },
}
